### ISSUE TITLE
大佬打包个docker可以吗

### ISSUE THREAD

**Issue by 2328760190** [isinvon/gold-foil-font-api#1]

**Comment by isinvon** [comment]
上次是想做docker的，网络太差了就没搞成，这几天我研究研究。

**Comment by isinvon** [comment]
@2328760190 docker镜像做好了, 安装步骤➡️ https://github.com/isinvon/gold-foil-font-api/tree/docker?tab=readme-ov-file#docker-%E5%AE%89%E8%A3%85

**Comment by 2328760190** [comment]
冒昧问一下，docker版是没有gui的吧，怎么搭配releases里的gui
