### ISSUE TITLE
坐等大佬的docker版本呀

### ISSUE THREAD

**Issue by yukikaze1234** [isinvon/gold-foil-font-api#3]
坐等大佬的docker版本呀，大佬加油！

**Comment by isinvon** [comment]
@yukikaze1234 还在docker分支上做测试, 最近比较忙请见谅.

**Comment by isinvon** [comment]
@yukikaze1234 docker镜像已经做好了➡️https://github.com/isinvon/gold-foil-font-api/tree/docker?tab=readme-ov-file#docker-%E5%AE%89%E8%A3%85

**Comment by yukikaze1234** [comment]
> @yukikaze1234 docker镜像已经做好了➡️https://github.com/isinvon/gold-foil-font-api/tree/docker?tab=readme-ov-file#docker-%E5%AE%89%E8%A3%85

老哥， 容器启动就报错。
<img width="808" alt="image" src="https://github.com/user-attachments/assets/fe452d37-07a3-4312-a9d8-03b62fcf5f88" />

**Comment by isinvon** [comment]
@yukikaze1234 感谢反馈, 最新commit做出了修改:https://github.com/isinvon/gold-foil-font-api/commit/c48f983872b496e86ec894e4089b829b604a8bc1  开发的时候前端忘记移除临时的baseurl了，现已在服务器上测试通过。

移除旧的镜像和容器, 然后重新 git clone 构建镜像再运行就可以了

**Comment by yukikaze1234** [comment]
> > @yukikaze1234 docker镜像已经做好了➡️https://github.com/isinvon/gold-foil-font-api/tree/docker?tab=readme-ov-file#docker-%E5%AE%89%E8%A3%85
> 
> 老哥， 容器启动就报错。 <img alt="image" width="808" src="https://private-user-images.githubusercontent.com/34395945/398337262-fe452d37-07a3-4312-a9d8-03b62fcf5f88.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUwOTQwODEsIm5iZiI6MTczNTA5Mzc4MSwicGF0aCI6Ii8zNDM5NTk0NS8zOTgzMzcyNjItZmU0NTJkMzctMDdhMy00MzEyLWE5ZDgtMDNiNjJmY2Y1Zjg4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI1VDAyMjk0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThiM2NkMmNiMzNmNDQwZDY3YThkMzc1ZjcxOTRkYjY1Y2I1N2ViYTc0Y2IyMWY1MWE4NTI2ZjA2MGUxNzUxZjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.RPEnEY7It-mrCuerPYf5p7PZMdFCc4WX0LlFbwAsa3U">

新的容器OK了！感谢作者
